---
unpack:
    -   source: "/run/live/medium/live/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""
        exclude:
            - "home/*"
            - "root/*"
            - "tmp/*"
            - "var/cache/*"
            - "var/log/*"
