# Foxiwium Linux — Calamares installer configuration
# Syntax is YAML 1.2
---

# "local" is LIBDIR/calamares/modules with settings in SHARE/calamares/modules
modules-search: [ local, /usr/lib/calamares/modules ]

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

sequence:
# Phase 1 — prepare (UI pages + immediate jobs).
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

# Phase 2 — install (jobs only).
- exec:
  - partition
  - mount
  - unpackfs
  - foxiwium-finalize
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - foxiwium-bootloader-config
  - grubcfg
  - bootloader
  - initramfscfg
  - initramfs
  - umount

# Phase 3 — postinstall.
- show:
  - finished

branding: foxiwium
prompt-install: false
dont-chroot: false
